package br.com.steventung.redegram.mlkit

const val UNIDENTIFIED_LANGUAGE_TAG = "unidentified language"

val translatableLanguageModels = mapOf(
    "af" to "africâner",
    "ar" to "árabe",
    "be" to "bielorrusso",
    "bg" to "búlgaro",
    "bn" to "bengali",
    "ca" to "catalão",
    "cs" to "tcheco",
    "cy" to "galês",
    "da" to "dinamarquês",
    "de" to "alemão",
    "el" to "grego",
    "en" to "inglês",
    "eo" to "esperanto",
    "es" to "espanhol",
    "et" to "estoniano",
    "fa" to "persa",
    "fi" to "finlandês",
    "fr" to "francês",
    "ga" to "irlandês",
    "gl" to "galego",
    "gu" to "gujarati",
    "he" to "hebraico",
    "hi" to "hindi",
    "hr" to "croata",
    "ht" to "haitiano",
    "hu" to "húngaro",
    "id" to "indonésio",
    "is" to "islandês",
    "it" to "italiano",
    "ja" to "japonês",
    "ka" to "georgiano",
    "km" to "khmer",
    "kn" to "canarim (kannada)",
    "ko" to "coreano",
    "lt" to "lituano",
    "lv" to "letão",
    "mk" to "macedônio",
    "mr" to "marata",
    "ms" to "malaio",
    "mt" to "maltês",
    "nl" to "holandês",
    "no" to "norueguês",
    "pl" to "polonês",
    "pt" to "português",
    "ro" to "romeno",
    "ru" to "russo",
    "sk" to "eslovaco",
    "sl" to "esloveno",
    "sq" to "albanês",
    "sv" to "sueco",
    "sw" to "suaíli",
    "ta" to "tâmil",
    "te" to "télugo",
    "th" to "tailandês",
    "tl" to "tagalo",
    "tr" to "turco",
    "uk" to "ucraniano",
    "ur" to "urdu",
    "vi" to "vietnamita",
    "zh" to "chinês",
)